### ISSUE TITLE
Hat-System variation, paying my dues :)

### ISSUE THREAD

**Issue by apetrynet** [fellesverkstedet/hat-systems#2]
Hey!

I just wanted to let you know that I'm creating a [variation](https://github.com/apetrynet/bunk_drawers) of the Hat-System for storage under my summer cabin bunk bed.

Thanks for this awesome design!

**Comment by JensDyvik** [comment]
Super awesome to see Daniel. Thank your for sharing the link! And great to see you are working with freecad. I have grown very fund of working with freecad lately. Especially using the a spreadsheet with aliases as a parametric design interface/driver
